# Generated by Django 3.0.6 on 2020-05-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='first name', max_length=64),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='last name', max_length=64),
        ),
    ]
