# Generated by Django 3.0.6 on 2020-05-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20200504_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Library'),
        ),
    ]
