# Generated by Django 3.0.6 on 2020-05-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_client_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
