# Generated by Django 3.0.6 on 2020-05-04 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_auto_20200504_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='given_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 19, 36, 30, 165558)),
        ),
        migrations.AlterField(
            model_name='carditem',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 19, 36, 30, 165558)),
        ),
    ]
